-- OZONTECK — notificações de novos produtos por interesse (backend-first).
-- Aplicar com as feature flags desativadas. O trigger apenas cria outbox;
-- nenhum e-mail é enviado dentro da transação de cadastro do produto.

begin;

create table if not exists public.customer_visitor_links (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  visitor_id text not null,
  last_session_id text,
  source text not null default 'authenticated_store',
  is_verified boolean not null default true,
  first_linked_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  profile_refreshed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint customer_visitor_links_visitor_length_chk
    check (char_length(visitor_id) between 1 and 180),
  constraint customer_visitor_links_session_length_chk
    check (last_session_id is null or char_length(last_session_id) between 1 and 180),
  constraint customer_visitor_links_source_length_chk
    check (char_length(source) between 1 and 60),
  constraint customer_visitor_links_customer_visitor_uk unique (customer_id, visitor_id),
  constraint customer_visitor_links_visitor_uk unique (visitor_id)
);

create table if not exists public.customer_interest_profiles (
  customer_id uuid not null references public.customers(id) on delete cascade,
  category_key text not null,
  category_label text not null,
  category_score numeric(5,2) not null,
  confidence numeric(5,2) not null,
  qualifying_signal_count integer not null default 0,
  signal_counts jsonb not null default '{}'::jsonb,
  last_signal_at timestamptz,
  profile_version text not null,
  calculated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (customer_id, category_key),
  constraint customer_interest_profiles_category_key_length_chk
    check (char_length(category_key) between 1 and 120),
  constraint customer_interest_profiles_category_label_length_chk
    check (char_length(category_label) between 1 and 120),
  constraint customer_interest_profiles_category_score_chk
    check (category_score between 0 and 100),
  constraint customer_interest_profiles_confidence_chk
    check (confidence between 0 and 100),
  constraint customer_interest_profiles_qualifying_signals_chk
    check (qualifying_signal_count >= 0)
);

create table if not exists public.customer_marketing_suppressions (
  customer_id uuid not null references public.customers(id) on delete cascade,
  channel text not null default 'email',
  reason text not null default 'customer_unsubscribe',
  suppressed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (customer_id, channel),
  constraint customer_marketing_suppressions_channel_chk
    check (channel in ('email')),
  constraint customer_marketing_suppressions_reason_length_chk
    check (char_length(reason) between 1 and 120)
);

create table if not exists public.product_notification_campaigns (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  campaign_type text not null default 'new_product_interest',
  category_key text,
  product_snapshot jsonb not null default '{}'::jsonb,
  status text not null default 'queued',
  summary jsonb not null default '{}'::jsonb,
  last_error text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_notification_campaigns_type_chk
    check (campaign_type in ('new_product_interest')),
  constraint product_notification_campaigns_status_chk
    check (status in ('queued', 'processing', 'completed', 'failed')),
  constraint product_notification_campaigns_product_type_uk
    unique (product_id, campaign_type)
);

create table if not exists public.product_notification_jobs (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.product_notification_campaigns(id) on delete cascade,
  job_type text not null default 'new_product_campaign',
  status text not null default 'queued',
  payload jsonb not null default '{}'::jsonb,
  attempts integer not null default 0,
  max_attempts integer not null default 3,
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  locked_by text,
  last_error text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_notification_jobs_type_chk
    check (job_type in ('new_product_campaign')),
  constraint product_notification_jobs_status_chk
    check (status in ('queued', 'processing', 'retry', 'completed', 'failed')),
  constraint product_notification_jobs_attempts_chk
    check (attempts >= 0 and max_attempts between 1 and 10),
  constraint product_notification_jobs_campaign_type_uk unique (campaign_id, job_type)
);

create table if not exists public.customer_notification_deliveries (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.product_notification_campaigns(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  channel text not null default 'email',
  category_key text not null,
  match_score numeric(5,2) not null,
  status text not null default 'pending',
  provider_message_id text,
  failure_reason text,
  metadata jsonb not null default '{}'::jsonb,
  sent_at timestamptz,
  simulated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint customer_notification_deliveries_channel_chk
    check (channel in ('email')),
  constraint customer_notification_deliveries_status_chk
    check (status in ('pending', 'simulated', 'sent', 'skipped', 'failed')),
  constraint customer_notification_deliveries_match_score_chk
    check (match_score between 0 and 100),
  constraint customer_notification_deliveries_dedupe_uk
    unique (campaign_id, customer_id, channel)
);

create index if not exists customer_visitor_links_visitor_last_seen_idx
  on public.customer_visitor_links (visitor_id, last_seen_at desc);

create index if not exists customer_visitor_links_refresh_idx
  on public.customer_visitor_links (profile_refreshed_at, last_seen_at desc)
  where is_verified = true;

create index if not exists customer_interest_profiles_match_idx
  on public.customer_interest_profiles
  (category_key, category_score desc, confidence desc, last_signal_at desc);

create index if not exists product_notification_jobs_ready_idx
  on public.product_notification_jobs (available_at, id)
  where status in ('queued', 'retry');

create index if not exists product_notification_jobs_lease_idx
  on public.product_notification_jobs (locked_at, id)
  where status = 'processing';

create index if not exists customer_notification_deliveries_frequency_idx
  on public.customer_notification_deliveries (customer_id, channel, created_at desc)
  where status in ('pending', 'simulated', 'sent');

alter table public.customer_visitor_links enable row level security;
alter table public.customer_interest_profiles enable row level security;
alter table public.customer_marketing_suppressions enable row level security;
alter table public.product_notification_campaigns enable row level security;
alter table public.product_notification_jobs enable row level security;
alter table public.customer_notification_deliveries enable row level security;

revoke all on table public.customer_visitor_links from public, anon, authenticated;
revoke all on table public.customer_interest_profiles from public, anon, authenticated;
revoke all on table public.customer_marketing_suppressions from public, anon, authenticated;
revoke all on table public.product_notification_campaigns from public, anon, authenticated;
revoke all on table public.product_notification_jobs from public, anon, authenticated;
revoke all on table public.customer_notification_deliveries from public, anon, authenticated;

grant select, insert, update, delete on table public.customer_visitor_links to service_role;
grant select, insert, update, delete on table public.customer_interest_profiles to service_role;
grant select, insert, update, delete on table public.customer_marketing_suppressions to service_role;
grant select, insert, update, delete on table public.product_notification_campaigns to service_role;
grant select, insert, update, delete on table public.product_notification_jobs to service_role;
grant select, insert, update, delete on table public.customer_notification_deliveries to service_role;
grant usage, select on sequence public.product_notification_jobs_id_seq to service_role;

create or replace function public.claim_product_notification_jobs(
  p_worker_id text,
  p_limit integer default 10,
  p_lease_seconds integer default 300
)
returns setof public.product_notification_jobs
language sql
security invoker
set search_path = ''
as $$
  with candidates as (
    select job.id
    from public.product_notification_jobs as job
    where job.attempts < job.max_attempts
      and (
        (
          job.status in ('queued', 'retry')
          and job.available_at <= now()
        )
        or (
          job.status = 'processing'
          and job.locked_at < now() - make_interval(secs => greatest(30, least(3600, p_lease_seconds)))
        )
      )
    order by job.available_at asc, job.id asc
    for update skip locked
    limit greatest(1, least(100, p_limit))
  )
  update public.product_notification_jobs as job
  set status = 'processing',
      attempts = job.attempts + 1,
      locked_at = now(),
      locked_by = left(coalesce(p_worker_id, 'unknown-worker'), 180),
      updated_at = now()
  from candidates
  where job.id = candidates.id
  returning job.*;
$$;

revoke execute on function public.claim_product_notification_jobs(text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.claim_product_notification_jobs(text, integer, integer)
  to service_role;

create or replace function public.reserve_product_interest_delivery(
  p_campaign_id uuid,
  p_customer_id uuid,
  p_category_key text,
  p_match_score numeric,
  p_metadata jsonb,
  p_daily_cap integer,
  p_weekly_cap integer,
  p_dry_run boolean
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_delivery_id uuid;
  v_now timestamptz := now();
  v_daily_count integer := 0;
  v_weekly_count integer := 0;
  v_counted_statuses text[];
begin
  -- Serializa somente as reservas deste cliente/canal. Assim, campanhas
  -- diferentes processadas por workers distintos não ultrapassam os caps.
  perform pg_advisory_xact_lock(
    hashtextextended(p_customer_id::text || ':product-interest-email', 0)
  );

  if exists (
    select 1
    from public.customer_notification_deliveries as delivery
    where delivery.campaign_id = p_campaign_id
      and delivery.customer_id = p_customer_id
      and delivery.channel = 'email'
  ) then
    return null;
  end if;

  -- Simulação considera simulações anteriores para reproduzir os caps.
  -- Produção ignora simulações, mas conta reservas pendentes para evitar corrida.
  v_counted_statuses := case
    when coalesce(p_dry_run, false)
      then array['pending', 'simulated', 'sent']::text[]
    else array['pending', 'sent']::text[]
  end;

  if greatest(0, coalesce(p_daily_cap, 0)) > 0 then
    select count(*)::integer
    into v_daily_count
    from public.customer_notification_deliveries as delivery
    where delivery.customer_id = p_customer_id
      and delivery.channel = 'email'
      and delivery.status = any(v_counted_statuses)
      and delivery.created_at >= v_now - interval '24 hours';

    if v_daily_count >= greatest(0, p_daily_cap) then
      return null;
    end if;
  end if;

  if greatest(0, coalesce(p_weekly_cap, 0)) > 0 then
    select count(*)::integer
    into v_weekly_count
    from public.customer_notification_deliveries as delivery
    where delivery.customer_id = p_customer_id
      and delivery.channel = 'email'
      and delivery.status = any(v_counted_statuses)
      and delivery.created_at >= v_now - interval '7 days';

    if v_weekly_count >= greatest(0, p_weekly_cap) then
      return null;
    end if;
  end if;

  insert into public.customer_notification_deliveries (
    campaign_id,
    customer_id,
    channel,
    category_key,
    match_score,
    status,
    metadata,
    simulated_at,
    created_at,
    updated_at
  )
  values (
    p_campaign_id,
    p_customer_id,
    'email',
    left(p_category_key, 120),
    greatest(0, least(100, p_match_score)),
    case when coalesce(p_dry_run, false) then 'simulated' else 'pending' end,
    coalesce(p_metadata, '{}'::jsonb),
    case when coalesce(p_dry_run, false) then v_now else null end,
    v_now,
    v_now
  )
  on conflict (campaign_id, customer_id, channel) do nothing
  returning id into v_delivery_id;

  return v_delivery_id;
end;
$$;

revoke execute on function public.reserve_product_interest_delivery(
  uuid, uuid, text, numeric, jsonb, integer, integer, boolean
) from public, anon, authenticated;

grant execute on function public.reserve_product_interest_delivery(
  uuid, uuid, text, numeric, jsonb, integer, integer, boolean
) to service_role;

create or replace function public.suppress_customer_product_marketing(
  p_customer_id uuid,
  p_reason text default 'customer_unsubscribe'
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  insert into public.customer_marketing_suppressions (
    customer_id,
    channel,
    reason,
    suppressed_at,
    updated_at
  )
  values (
    p_customer_id,
    'email',
    left(coalesce(nullif(trim(p_reason), ''), 'customer_unsubscribe'), 120),
    now(),
    now()
  )
  on conflict (customer_id, channel)
  do update set
    reason = excluded.reason,
    suppressed_at = excluded.suppressed_at,
    updated_at = excluded.updated_at;

  update public.customers
  set newsletter_opt_in = false,
      updated_at = now()
  where id = p_customer_id;
end;
$$;

revoke execute on function public.suppress_customer_product_marketing(uuid, text)
  from public, anon, authenticated;
grant execute on function public.suppress_customer_product_marketing(uuid, text)
  to service_role;

create or replace function public.enqueue_new_product_interest_campaign()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_campaign_id uuid;
  v_is_eligible boolean;
  v_was_eligible boolean := false;
begin
  v_is_eligible := lower(trim(coalesce(new.status, ''))) = 'active'
    and coalesce(new.stock_quantity, 0) > 0;

  if not v_is_eligible then
    return new;
  end if;

  if tg_op = 'UPDATE' then
    v_was_eligible := lower(trim(coalesce(old.status, ''))) = 'active'
      and coalesce(old.stock_quantity, 0) > 0;
    if v_was_eligible then
      return new;
    end if;
  end if;

  begin
    insert into public.product_notification_campaigns (
      product_id,
      campaign_type,
      product_snapshot,
      status
    )
    values (
      new.id,
      'new_product_interest',
      jsonb_build_object(
        'id', new.id,
        'name', new.name,
        'sku', new.sku,
        'category', new.category,
        'price', new.price,
        'status', new.status,
        'stock_quantity', new.stock_quantity,
        'image_url', new.image_url
      ),
      'queued'
    )
    on conflict (product_id, campaign_type) do nothing
    returning id into v_campaign_id;

    if v_campaign_id is not null then
      insert into public.product_notification_jobs (campaign_id, job_type, status)
      values (v_campaign_id, 'new_product_campaign', 'queued')
      on conflict (campaign_id, job_type) do nothing;
    end if;
  exception
    when others then
      -- A indisponibilidade do módulo de marketing nunca bloqueia o produto.
      raise warning 'OZONTECK product interest outbox failed for product %: %', new.id, sqlerrm;
  end;

  return new;
end;
$$;

revoke execute on function public.enqueue_new_product_interest_campaign()
  from public, anon, authenticated;

drop trigger if exists products_enqueue_new_interest_campaign
  on public.products;

create trigger products_enqueue_new_interest_campaign
after insert or update of status, stock_quantity on public.products
for each row
execute function public.enqueue_new_product_interest_campaign();

comment on table public.customer_interest_profiles is
  'Projeção do intent-v1.2 para seleção de novidades; não contém histórico bruto de navegação.';
comment on table public.customer_notification_deliveries is
  'Deduplicação e auditoria de e-mails de novidades por cliente e campanha.';
comment on function public.claim_product_notification_jobs(text, integer, integer) is
  'Reivindica jobs com lease usando FOR UPDATE SKIP LOCKED; execução exclusiva do service_role.';
comment on function public.reserve_product_interest_delivery(
  uuid, uuid, text, numeric, jsonb, integer, integer, boolean
) is
  'Reserva uma entrega com deduplicação e caps diário/semanal serializados por cliente.';

commit;
